name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # specify the Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress tests
        run: |
          npx cypress run --reporter mocha-junit-reporter --reporter-options "mochaFile=reports/junit-[hash].xml"

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: reports/*.xml

      - name: Upload video recordings
        uses: actions/upload-artifact@v2
        with:
          name: test-videos
          path: cypress/videos

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: test-screenshots
          path: cypress/screenshots
