name: Cypress E2E Tests

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    # Steps to set up the environment and run Cypress tests
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate fake data for testing
        run: npm run generate-fake-data

      - name: Run Cypress tests
        run: npx cypress run

      # Optional: Generate and display test report using mochawesome
      - name: Generate Cypress report
        run: npm run test:report

      # Uploading test artifacts for later review (screenshots, videos, etc.)
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            cypress/reports
